### ISSUE TITLE
single-day opt-ins

### ISSUE THREAD

**Issue by courajs** [chrobid/pairing-bot#1] opened 2019-06-17 22:12 UTC
It would be cool to be able to do the opposite of skip a day - opt in to pairing tomorrow without changing my schedule!

**Comment by chrobid** [comment] 2019-06-19 01:31
I agree! Hopefully I'll get time to work on this this week.

**Comment by chrobid** [comment] 2019-06-20 02:50
Duplicate of #2

**Comment by chrobid** [comment] 2019-06-20 02:51
Duplicate of #2 

Sorry I'm still getting the hang of the issue tracker :)

**Closed by chrobid** 2019-06-20 02:51 UTC
